### ISSUE TITLE
Godot for mobile

### ISSUE THREAD

**Issue by gattila** [godot-extended-libraries/godot-ideas#4]
I am not sure whether it is a good place to do this suggestion or not, but IMHO creating a mobile version of the Godot editor, like AppGameKit mobile can be a good idea.

Probably nobody will develop the Skyrim 6 on mobile, but if you have a tablet and you are for example on vacation, you can learn Godot or try your ideas. And you can have a feeling that your favorite game development environment is always with you :-)

And if it is available in the Google Play, IMHO many people show it and try it, and maybe pay for it, in spite that the Godot is available freely. It can be another way to support the project.

**Comment by willnationsdev** [comment]
> I am not sure whether it is a good place to do this suggestion or not

This is *exactly* the kind of place where this idea should go. ;-)

> IMHO creating a mobile version of the Godot editor, like AppGameKit mobile can be a good idea.

I think this *could* be possible, but it would definitely be a lot of work to do. The UI would have to be drastically modified to accommodate such a small screen, but I think it would be possible, just off the top of my head. I don't know what hurdles you would run into trying to redesign Godot that way though.

**Comment by Xrayez** [comment]
If only the Godot Editor could be overridden by script, so that you can write your own editor via GDScript! In theory it's currently possible to write a plugin which changes how the Godot's base root Control behaves and reacts to fit viewport size.

Zylann's [EditorDebugger ](https://github.com/Zylann/godot_editor_debugger_plugin)could be used to study Godot Editor internals that way.

**Comment by gattila** [comment]
At first, I don't want to a totally new user interface for mobile. It is a common mistake, that all application needs a totally new UI for mobile. I used godot on a windows tablet without too much problem. I also tried to compile it for android but with just partial success: the IDE was started, but the dialog boxes blinking, and our behavior was a little bit incorrect. I was unable to create a new project with it.

**Comment by Xrayez** [comment]
It might be that there are permission problems on Android/iPhone, where `res://` is not writable (while `user://` is writable, for most platforms).

Also I stumbled upon [Raspberry Pi 4 article](https://bits.krzysztofjankowski.com/raspberry-pi-4-as-perfect-indie-console/) some time ago which might be related.

**Comment by rxlecky** [comment]
This is actually planned. 🙂 They will be porting editor to browsers which will essentially allow you to use it on any device - including mobile. 

See section WP1:
https://godotengine.org/article/godot-engine-awarded-50000-mozilla-open-source-support-program

**Comment by aaronfranke** [comment]
This is tracked by Godot here: https://github.com/godotengine/godot/issues/267

**Comment by Calinou** [comment]
Since this is now being tracked in https://github.com/godotengine/godot-proposals/issues/1061, this issue could be closed.

**Comment by Xrayez** [comment]
Closing for now then. 😛
